# Generated by Django 4.2.7 on 2025-07-22 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightsearch',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='flightroute',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_destinations', to='flights.airport'),
        ),
        migrations.AddField(
            model_name='flightroute',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_origins', to='flights.airport'),
        ),
        migrations.AddField(
            model_name='flightdeal',
            name='airline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flights.airline'),
        ),
        migrations.AddField(
            model_name='flightdeal',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flights.flightroute'),
        ),
        migrations.AddField(
            model_name='flightclass',
            name='flight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='flights.flight'),
        ),
        migrations.AddField(
            model_name='flight',
            name='airline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.airline'),
        ),
        migrations.AddField(
            model_name='flight',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arriving_flights', to='flights.airport'),
        ),
        migrations.AddField(
            model_name='flight',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departing_flights', to='flights.airport'),
        ),
        migrations.AddField(
            model_name='airport',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airports', to='core.city'),
        ),
        migrations.AlterUniqueTogether(
            name='flightroute',
            unique_together={('origin', 'destination')},
        ),
        migrations.AlterUniqueTogether(
            name='flightclass',
            unique_together={('flight', 'class_type')},
        ),
    ]
