# Generated by Django 4.2.7 on 2026-01-04 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners_dashboard', '0001_initial'),
        ('tours', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='partner_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tours', to='partners_dashboard.partner'),
        ),
    ]
