# Generated by Django 4.2.7 on 2026-01-02 23:32

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('affiliates', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='affiliatecommission',
            old_name='booking_amount_currency',
            new_name='amount_currency',
        ),
        migrations.RenameField(
            model_name='affiliatereferral',
            old_name='created_at',
            new_name='referred_at',
        ),
        migrations.RemoveField(
            model_name='affiliatecommission',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='affiliatecommission',
            name='booking_amount',
        ),
        migrations.RemoveField(
            model_name='affiliatecommission',
            name='commission_amount',
        ),
        migrations.RemoveField(
            model_name='affiliatecommission',
            name='commission_amount_currency',
        ),
        migrations.RemoveField(
            model_name='affiliatecommission',
            name='commission_rate',
        ),
        migrations.RemoveField(
            model_name='affiliatecommission',
            name='referral',
        ),
        migrations.RemoveField(
            model_name='affiliatereferral',
            name='first_booking_amount',
        ),
        migrations.RemoveField(
            model_name='affiliatereferral',
            name='first_booking_amount_currency',
        ),
        migrations.RemoveField(
            model_name='affiliatereferral',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='affiliatereferral',
            name='referral_source',
        ),
        migrations.RemoveField(
            model_name='affiliatereferral',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='affiliatecommission',
            name='amount',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='affiliatecommission',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='affiliatecommission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('paid', 'Paid'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='affiliatereferral',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='affiliatereferral',
            name='referred_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='affiliatereferral',
            name='user_agent',
            field=models.TextField(),
        ),
    ]
