# Generated by Django 4.2.7 on 2026-06-03 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenuereport',
            name='service_type',
            field=models.CharField(choices=[('hotel', 'Hotels'), ('flight', 'Flights'), ('car', 'Car Rentals'), ('tour', 'Tours'), ('event', 'Event')], max_length=20),
        ),
    ]
