# Generated by Django 4.2.7 on 2025-07-22 19:15

from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('address', models.TextField()),
                ('star_rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3)),
                ('price_per_night_currency', djmoney.models.fields.CurrencyField(choices=[('AUD', 'Australian Dollar'), ('GBP', 'British Pound'), ('CAD', 'Canadian Dollar'), ('CNY', 'Chinese Yuan'), ('EUR', 'Euro'), ('JPY', 'Japanese Yen'), ('NZD', 'New Zealand Dollar'), ('SEK', 'Swedish Krona'), ('CHF', 'Swiss Franc'), ('USD', 'US Dollar')], default='USD', editable=False, max_length=3)),
                ('price_per_night', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=10)),
                ('amenities', models.JSONField(blank=True, default=list)),
                ('main_image', models.ImageField(blank=True, upload_to='hotels/')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('check_in_time', models.TimeField(default='14:00')),
                ('check_out_time', models.TimeField(default='11:00')),
                ('cancellation_policy', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('partner_commission', models.DecimalField(decimal_places=2, default=15.0, max_digits=5)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='core.city')),
            ],
            options={
                'ordering': ['-is_featured', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HotelFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('category', models.CharField(choices=[('general', 'General'), ('business', 'Business'), ('fitness', 'Fitness & Recreation'), ('internet', 'Internet'), ('parking', 'Parking'), ('services', 'Services'), ('accessibility', 'Accessibility')], max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('max_occupancy', models.IntegerField(default=2)),
                ('price_per_night_currency', djmoney.models.fields.CurrencyField(choices=[('AUD', 'Australian Dollar'), ('GBP', 'British Pound'), ('CAD', 'Canadian Dollar'), ('CNY', 'Chinese Yuan'), ('EUR', 'Euro'), ('JPY', 'Japanese Yen'), ('NZD', 'New Zealand Dollar'), ('SEK', 'Swedish Krona'), ('CHF', 'Swiss Franc'), ('USD', 'US Dollar')], default='USD', editable=False, max_length=3)),
                ('price_per_night', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=10)),
                ('size_sqm', models.IntegerField(blank=True, null=True)),
                ('bed_type', models.CharField(blank=True, max_length=50)),
                ('amenities', models.JSONField(blank=True, default=list)),
                ('total_rooms', models.IntegerField(default=1)),
                ('available_rooms', models.IntegerField(default=1)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_types', to='hotels.hotel')),
            ],
            options={
                'ordering': ['price_per_night'],
            },
        ),
        migrations.CreateModel(
            name='HotelPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('partner_name', models.CharField(max_length=200)),
                ('partner_id', models.CharField(max_length=100, unique=True)),
                ('api_endpoint', models.URLField(blank=True)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=15.0, max_digits=5)),
                ('api_key', models.CharField(blank=True, max_length=255)),
                ('api_secret', models.CharField(blank=True, max_length=255)),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('hotel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='partner', to='hotels.hotel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HotelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to='hotels/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='hotels.hotel')),
            ],
            options={
                'ordering': ['-is_primary', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HotelAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('available_rooms', models.IntegerField(default=0)),
                ('price_per_night_currency', djmoney.models.fields.CurrencyField(choices=[('AUD', 'Australian Dollar'), ('GBP', 'British Pound'), ('CAD', 'Canadian Dollar'), ('CNY', 'Chinese Yuan'), ('EUR', 'Euro'), ('JPY', 'Japanese Yen'), ('NZD', 'New Zealand Dollar'), ('SEK', 'Swedish Krona'), ('CHF', 'Swiss Franc'), ('USD', 'US Dollar')], default='USD', editable=False, max_length=3)),
                ('price_per_night', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=10)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='hotels.hotel')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('hotel', 'date')},
            },
        ),
    ]
