# Generated by Django 4.2.7 on 2025-07-28 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='site_description',
            field=models.CharField(default='your best travel service', max_length=1000),
        ),
    ]
