# Generated by Django 4.2.7 on 2025-12-15 23:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(db_index=True, max_length=128)),
                ('payload', models.JSONField()),
                ('signature', models.CharField(blank=True, max_length=256)),
                ('processed', models.BooleanField(db_index=True, default=False)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Webhook Event',
                'verbose_name_plural': 'Webhook Events',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(db_index=True, max_length=128, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('amount', models.BigIntegerField(help_text='Amount in smallest currency unit (e.g. kobo/cents)')),
                ('currency', models.CharField(default='NGN', max_length=8)),
                ('service_type', models.CharField(blank=True, help_text="Optional: service type this payment is for (e.g. 'booking', 'order')", max_length=50)),
                ('service_id', models.CharField(blank=True, help_text='Optional: related service id', max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('gateway_response', models.JSONField(blank=True, null=True)),
                ('paid', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['reference'], name='payments_pa_referen_72073c_idx'), models.Index(fields=['status'], name='payments_pa_status_b6726a_idx')],
            },
        ),
    ]
