# Generated by Django 4.2.7 on 2025-07-22 19:15

from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, upload_to='car_brands/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.carbrand')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CarRental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('pickup_location', models.CharField(max_length=200)),
                ('pickup_address', models.TextField()),
                ('year', models.IntegerField()),
                ('color', models.CharField(blank=True, max_length=50)),
                ('license_plate', models.CharField(blank=True, max_length=20)),
                ('category', models.CharField(choices=[('economy', 'Economy'), ('compact', 'Compact'), ('intermediate', 'Intermediate'), ('standard', 'Standard'), ('full_size', 'Full Size'), ('premium', 'Premium'), ('luxury', 'Luxury'), ('suv', 'SUV'), ('minivan', 'Minivan'), ('convertible', 'Convertible')], max_length=50)),
                ('passengers', models.IntegerField(default=4)),
                ('bags', models.IntegerField(default=2)),
                ('doors', models.IntegerField(default=4)),
                ('transmission', models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic')], default='automatic', max_length=20)),
                ('fuel_type', models.CharField(choices=[('gasoline', 'Gasoline'), ('diesel', 'Diesel'), ('hybrid', 'Hybrid'), ('electric', 'Electric')], default='gasoline', max_length=20)),
                ('air_conditioning', models.BooleanField(default=True)),
                ('gps', models.BooleanField(default=False)),
                ('price_per_day_currency', djmoney.models.fields.CurrencyField(choices=[('AUD', 'Australian Dollar'), ('GBP', 'British Pound'), ('CAD', 'Canadian Dollar'), ('CNY', 'Chinese Yuan'), ('EUR', 'Euro'), ('JPY', 'Japanese Yen'), ('NZD', 'New Zealand Dollar'), ('SEK', 'Swedish Krona'), ('CHF', 'Swiss Franc'), ('USD', 'US Dollar')], default='USD', editable=False, max_length=3)),
                ('price_per_day', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=10)),
                ('price_per_week_currency', djmoney.models.fields.CurrencyField(choices=[('AUD', 'Australian Dollar'), ('GBP', 'British Pound'), ('CAD', 'Canadian Dollar'), ('CNY', 'Chinese Yuan'), ('EUR', 'Euro'), ('JPY', 'Japanese Yen'), ('NZD', 'New Zealand Dollar'), ('SEK', 'Swedish Krona'), ('CHF', 'Swiss Franc'), ('USD', 'US Dollar')], default='USD', editable=False, max_length=3, null=True)),
                ('price_per_week', djmoney.models.fields.MoneyField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_per_month_currency', djmoney.models.fields.CurrencyField(choices=[('AUD', 'Australian Dollar'), ('GBP', 'British Pound'), ('CAD', 'Canadian Dollar'), ('CNY', 'Chinese Yuan'), ('EUR', 'Euro'), ('JPY', 'Japanese Yen'), ('NZD', 'New Zealand Dollar'), ('SEK', 'Swedish Krona'), ('CHF', 'Swiss Franc'), ('USD', 'US Dollar')], default='USD', editable=False, max_length=3, null=True)),
                ('price_per_month', djmoney.models.fields.MoneyField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('insurance_included', models.BooleanField(default=False)),
                ('insurance_cost_currency', djmoney.models.fields.CurrencyField(choices=[('AUD', 'Australian Dollar'), ('GBP', 'British Pound'), ('CAD', 'Canadian Dollar'), ('CNY', 'Chinese Yuan'), ('EUR', 'Euro'), ('JPY', 'Japanese Yen'), ('NZD', 'New Zealand Dollar'), ('SEK', 'Swedish Krona'), ('CHF', 'Swiss Franc'), ('USD', 'US Dollar')], default='USD', editable=False, max_length=3, null=True)),
                ('insurance_cost', djmoney.models.fields.MoneyField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('minimum_age', models.IntegerField(default=21)),
                ('driving_license_required', models.BooleanField(default=True)),
                ('credit_card_required', models.BooleanField(default=True)),
                ('security_deposit_currency', djmoney.models.fields.CurrencyField(choices=[('AUD', 'Australian Dollar'), ('GBP', 'British Pound'), ('CAD', 'Canadian Dollar'), ('CNY', 'Chinese Yuan'), ('EUR', 'Euro'), ('JPY', 'Japanese Yen'), ('NZD', 'New Zealand Dollar'), ('SEK', 'Swedish Krona'), ('CHF', 'Swiss Franc'), ('USD', 'US Dollar')], default='USD', editable=False, max_length=3)),
                ('security_deposit', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=10)),
                ('main_image', models.ImageField(blank=True, upload_to='car_rentals/')),
                ('mileage_limit', models.IntegerField(blank=True, null=True)),
                ('extra_mileage_cost_currency', djmoney.models.fields.CurrencyField(choices=[('AUD', 'Australian Dollar'), ('GBP', 'British Pound'), ('CAD', 'Canadian Dollar'), ('CNY', 'Chinese Yuan'), ('EUR', 'Euro'), ('JPY', 'Japanese Yen'), ('NZD', 'New Zealand Dollar'), ('SEK', 'Swedish Krona'), ('CHF', 'Swiss Franc'), ('USD', 'US Dollar')], default='USD', editable=False, max_length=3, null=True)),
                ('extra_mileage_cost', djmoney.models.fields.MoneyField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.carmodel')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_rentals', to='core.city')),
            ],
            options={
                'ordering': ['price_per_day'],
            },
        ),
        migrations.CreateModel(
            name='CarRentalCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, upload_to='car_companies/')),
                ('website', models.URLField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CarRentalExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price_currency', djmoney.models.fields.CurrencyField(choices=[('AUD', 'Australian Dollar'), ('GBP', 'British Pound'), ('CAD', 'Canadian Dollar'), ('CNY', 'Chinese Yuan'), ('EUR', 'Euro'), ('JPY', 'Japanese Yen'), ('NZD', 'New Zealand Dollar'), ('SEK', 'Swedish Krona'), ('CHF', 'Swiss Franc'), ('USD', 'US Dollar')], default='USD', editable=False, max_length=3)),
                ('price', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=10)),
                ('price_type', models.CharField(choices=[('per_day', 'Per Day'), ('per_rental', 'Per Rental'), ('per_week', 'Per Week')], default='per_day', max_length=20)),
                ('category', models.CharField(choices=[('navigation', 'Navigation'), ('child_safety', 'Child Safety'), ('comfort', 'Comfort'), ('protection', 'Protection'), ('mobility', 'Mobility')], max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CarRentalLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('opening_hours', models.JSONField(blank=True, default=dict)),
                ('location_type', models.CharField(choices=[('airport', 'Airport'), ('city_center', 'City Center'), ('hotel', 'Hotel'), ('train_station', 'Train Station'), ('other', 'Other')], default='city_center', max_length=50)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.city')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='cars.carrentalcompany')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CarRentalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to='car_rentals/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('car_rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cars.carrental')),
            ],
            options={
                'ordering': ['-is_primary', 'id'],
            },
        ),
        migrations.AddField(
            model_name='carrental',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.carrentalcompany'),
        ),
        migrations.CreateModel(
            name='CarRentalAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_available', models.BooleanField(default=True)),
                ('price_per_day_currency', djmoney.models.fields.CurrencyField(choices=[('AUD', 'Australian Dollar'), ('GBP', 'British Pound'), ('CAD', 'Canadian Dollar'), ('CNY', 'Chinese Yuan'), ('EUR', 'Euro'), ('JPY', 'Japanese Yen'), ('NZD', 'New Zealand Dollar'), ('SEK', 'Swedish Krona'), ('CHF', 'Swiss Franc'), ('USD', 'US Dollar')], default='USD', editable=False, max_length=3)),
                ('price_per_day', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=10)),
                ('car_rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='cars.carrental')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('car_rental', 'date')},
            },
        ),
    ]
